-- ARQUIVO: database.sql
-- SISTEMA: Bichos do Bairro - Estrutura do Banco
-- 
-- ⚠️  ATENÇÃO - ESTRUTURAS CRÍTICAS EM FUNCIONAMENTO:
-- ✅ Tabelas principais criadas
-- ✅ Relacionamentos funcionando
-- ✅ Índices otimizados
-- ✅ Constraints ativas
-- 
-- 🚨 NÃO ALTERE SEM BACKUP:
-- - Estrutura das tabelas principais
-- - Foreign keys existentes
-- - Índices de performance
-- - Triggers implementadas
-- 
-- 📝 REGRA DE OURO:
-- "Ao fazer upgrade ou alteração, NÃO MUDE NADA que já está funcionando"